---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net
  namespace: homeassistant
spec:
  config: '{
    "name": "mynet",
    "type": "macvlan",
    "mode": "bridge",
    "ipam": {
    "type": "static",
    "addresses": [
    {
    "address": "10.0.0.31/24"
    },
    {
    "address": "fd48:e380:751a:0::31/64"
    }
    ]
    }
    }'
