apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  strategy:
    type: Recreate
  template:
    strategy:
      type: Recreate
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2023.11.3
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: Europe/Berlin
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
