apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
