apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ryrPNw8=,iv:9z7wICBXSAnAV5CFCEHnJBXqMP/RB898m+FUqSwW7mg=,tag:ucGCUTUI2nSuTdZ2wmuMNw==,type:str]
    password: ENC[AES256_GCM,data:mw1vUyR+ewi+BKH213v2Cbk5rpBQYajjUeQ77EqCyLzfphYZvl5ZME+iqrxHPiaS3i5UGx6SqQNtwMgd,iv:Y/KFfb2avw1P6jwCteHPAQIeqgxXBaL7ZW8cYS25f/w=,tag:8W6zVOhjI48e1rWENtezww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-16T07:14:48Z"
    mac: ENC[AES256_GCM,data:kfg4LsnaD3eLSDf6JEBv0hVa2+5BY/0wEgOcHnH9EZO1PXP5l3MUbxEtJXuuo2vJsEfDNCoxJrelGaIpONFHHxa58tMyN1KGTvGptDjjqfnbZ/3hPvWdZGSWbb3X1nLZVeqrH2zlLdzgLm9/BNKE1jay5/TcwcpGbGGutMhLWPA=,iv:c/SLevabhO5esgkK9IsTEyAIrVJpZKtThq0uThFvAaI=,tag:Ifhzu/O9Gx5O2QZDKgRSIQ==,type:str]
    pgp:
        - created_at: "2023-04-16T07:14:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAziw5H14r1eiARAAk/TzJBYeBIfRCPRKkciY9/ITpMV5/PCg7eofFuItYDGN
            K3i5XbpFcf8o2KX0upjS1cd/n3GP8LyUWp5rLJ51Z+qLBvmsD2lSKLYA9yeOnQR6
            tdqKonbi8DCFuwKYO8kmWAKEXH2UAp9/qTR1YdDeduHYzTtXz2UBUyarzXhvCtRE
            U/xgdTauzRmKENM2z9+NR3qWStz8bKw/5Ca9vvYhlf7tkW+HOO7/gzkDb6hsjdn0
            o+INP9uDSW0wlqLHt5mygdDJmXChnYFhAZDVzcq1TYAGgMBRNs6xzTCVyIx3U2yL
            crwSyRr4GwM4ZfaLmkh4/DHhOba53/u8gGwQ9T18ulWxyVpjGptzW8ydSOKUe965
            JzkJ9gkRWKLOPmc1SzvRtHhvL7ss0WxSZkWaWtx8wU5kaRFpwb+N/NaV9U+YVb1K
            tjbNtTlxdnyjKkx9AKa2LjJ/+z9yhEFl/aHqqCkwkrZXsMOiIh/WfvQhPR6o5k81
            NI5EXDZiPHvoWJvOq87UYohihlKv6RBq23MGOJUYdDm2xqKgftoKuBrai1QT1s63
            n/QDOYk9y+iXRkvc9UTd0B5gGVrqL4+x1/Scz07MlrnSBUQUHGuIGFHgwlaKk2TE
            GP+X3tNlMgAMS1S37Odq3vhCNPqhFoQabALJWOwJVmaThlfOLe6n29v2UC91MSDU
            ZgEJAhA4kbiN6prXeWMd9X9B1piWgrXsBgQ08w4dxzf76UW/1/KhgKFQakqLviGC
            k+ycEgGEahOVeOMfJBN5D+aLzS1iAukrvL3BPDfIuszigLaBSdQE5SMaSab9J86Z
            EJW6RkmUZg==
            =FVCx
            -----END PGP MESSAGE-----
          fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
