---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoview
  namespace: photoview
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: photoview
  template:
    metadata:
      labels:
        app: photoview
    spec:
      containers:
        - name: photoview
          image: viktorstrate/photoview
          env:
            - name: PHOTOVIEW_DATABASE_DRIVER
              value: mysql
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
            - name: PHOTOVIEW_MYSQL_URL
              value: photoview:$(DB_PASS)@tcp(photoview-mariadb)/photoview
            - name: PHOTOVIEW_LISTEN_IP
              value: photoview
            - name: PHOTOVIEW_LISTEN_PORT
              value: "80"
            - name: PHOTOVIEW_MEDIA_CACHE
              value: /app/cache
            - name: PHOTOVIEW_DISABLE_VIDEO_ENCODING
              value: "1"
          ports:
            - name: photoview
              containerPort: 80
              hostPort: 80
          volumeMounts:
            - name: cache
              mountPath: /app/cache
            - name: media
              mountPath: /photos
              subPath: jonatan/Pictures
            - name: quicksync
              mountPath: /dev/dri
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: photoview-cache
        - name: media
          nfs:
            server: 10.0.0.11
            path: /tank/home
            readOnly: true
        - name: quicksync
          hostPath:
            path: /dev/dri
