---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: photoview-mariadb
  namespace: photoview
spec:
  rootPasswordSecretKeyRef:
    name: photoview-mariadb
    key: root-password

  database: photoview
  username: photoview
  passwordSecretKeyRef:
    name: photoview-mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 5Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
