---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoview-cache
  namespace: photoview
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
