---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-external
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-external
  template:
    metadata:
      labels:
        app: external-dns-external
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.13.5
          args:
            - --source=ingress
            - --domain-filter=jsteuernagel.de # (optional) limit to only example.com domains; change to match the zone created above.
            - --zone-id-filter=1af46885a182f9a6fe61dd067ea00ebf # (optional) limit to a specific zone.
            - --provider=cloudflare
            - --annotation-filter=external-dns.alpha.kubernetes.io/my-target in (external)
            - --txt-owner-id=home
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token-secret
                  key: api-token
