---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resilio-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  path: ./apps/resilio-sync/resilio-sync/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
