---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
#    - name: ingress-nginx
  path: ./apps/jellyfin/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
