---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game
  namespace: sons-of-the-forest
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winedata
  namespace: sons-of-the-forest
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
