---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: ">=6.0.0 <7.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    defaultDashboardsTimezone: browser

    admin:
      existingSecret: grafana-admin
      userKey: username
      passwordKey: password

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/my-target: internal
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/16
      hosts:
        - "grafana.k8s.jsteuernagel.de"
      tls:
        - hosts:
            - grafana.k8s.jsteuernagel.de
          secretName: grafana-k8s-jsteuernagel-de-tls

    #additionalDataSources:

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 4Gi

    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 40m
        memory: 160Mi

    grafana.ini:
      server:
        domain: "grafana.k8s.jsteuernagel.de"
        root_url: "https://%(domain)s/"

      alerting:
        enabled: true
