apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-sync-config
  namespace: resilio-sync
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
