---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: multus-cni
      version: "0.2.2"
      sourceRef:
        kind: HelmRepository
        name: multus
        namespace: flux-system
      interval: 12h
  values:
