---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: netdata
spec:
  interval: 30m
  chart:
    spec:
      chart: netdata
      version: "3.7.60"
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 12h
  values:
    image:
      tag: stable

    parent:
      envFrom:
        - secretRef:
            name: netdata-token
      claiming:
        enabled: true
      database:
        storageclass: longhorn
      alarms:
        storageclass: longhorn

    child:
      envFrom:
        - secretRef:
            name: netdata-token
      claiming:
        enabled: true

    k8sState:
      persistence:
        storageclass: longhorn
