---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  dependsOn:
    - name: mariadb-operator
    - name: redis-operator
  path: ./apps/paperless-ngx/paperless-ngx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
