apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config
  namespace: grocy
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
