---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 24h
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/script/helm/garage
