---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.26.0
  url: https://github.com/intel/intel-device-plugins-for-kubernetes.git

