---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: multus
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/k8snetworkplumbingwg/multus-cni.git
  ref:
    tag: v4.0.1
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/deployments
