---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts/
