---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      replicaCount: 3
      service:
        annotations:
          io.cilium/lb-ipam-ips: 10.0.1.10,fd48:e380:751a:1::10
        type: "LoadBalancer"
        externalTrafficPolicy: Local
        ipFamilyPolicy: RequireDualStack
