---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      kind: Deployment
      replicaCount: 2
      service:
        annotations:
          io.cilium/lb-ipam-ips: 10.0.1.10,fd48:e380:751a:1::10
        type: "LoadBalancer"
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
      allowSnippetAnnotations: true
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: controller
        topologyKey: kubernetes.io/hostname
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
    tcp:
      "22": "gitea/gitea-ssh:22"
