---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    minio:
      enabled: false

    global:
      extraEnvFrom:
        - secretRef:
            name: mimir-bucket-secret
      podAnnotations:
        bucketSecretVersion: "0"

    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: s3.jsteuernagel.de
              region: garage
              secret_access_key: "${AWS_SECRET_ACCESS_KEY}" # This is a secret injected via an environment variable
              access_key_id: "${AWS_ACCESS_KEY_ID}" # This is a secret injected via an environment variable

        blocks_storage:
          s3:
            bucket_name: mimir-blocks
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        ruler_storage:
          s3:
            bucket_name: mimir-ruler

    alertmanager:
      persistentVolume:
        storageClass: local-path
    compactor:
      persistentVolume:
        storageClass: local-path
    ingester:
      persistentVolume:
        storageClass: local-path
    store_gateway:
      persistentVolume:
        storageClass: local-path

    metaMonitoring:
      dashboards:
        enabled: true
      serviceMonitor:
        enabled: true
      grafanaAgent:
        enabled: true
        installOperator: true

    gateway:
      enabledNonEnterprise: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/my-target: internal
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/16
        hosts:
          - host: mimir.k8s.jsteuernagel.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - mimir.jsteuernagel.de
            secretName: mimir-jsteuernagel-de-tls
