---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    minio:
      enabled: false

    global:
      extraEnvFrom:
        - secretRef:
            name: mimir-bucket-secret
      podAnnotations:
        bucketSecretVersion: "0"

    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: s3.jsteuernagel.de
              region: garage
              # TODO: Create
              secret_access_key: "${AWS_SECRET_ACCESS_KEY}" # This is a secret injected via an environment variable
              access_key_id: "${AWS_ACCESS_KEY_ID}" # This is a secret injected via an environment variable

        blocks_storage:
          s3:
            bucket_name: mimir-blocks # TODO: Create
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager # TODO: Create
        ruler_storage:
          s3:
            bucket_name: mimir-ruler # TODO: Create

    metaMonitoring:
      dashboards:
        enabled: true
      serviceMonitor:
        enabled: true
      grafanaAgent:
        enabled: true
        installOperator: true
        metrics:
          additionalRemoteWriteConfigs:
            - url: "http://mimir-nginx.monitoring.svc:80/api/v1/push"

    gateway:
      enabledNonEnterprise: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/my-target: external
          external-dns.alpha.kubernetes.io/target: dyn.jsteuernagel.de
        hosts:
          - host: mimir.k8s.jsteuernagel.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - mimir.jsteuernagel.de
            secretName: mimir-jsteuernagel-de-tls
