apiVersion: v1
kind: Secret
metadata:
  name: mimir-bucket-secret
  namespace: monitoring
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6Mo8s3ogtq89nXUd8nMKhl600c9AiwsJqNI=,iv:hDYBYrVcQgtQ16c3AU+QDQ3eeSDut2Cv6zoOvkitBfw=,tag:K8UJkY7lEu884Knt75vKCg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E+4FofTxFNxANUNsSNq8616YTBYCESX/Cp427+NuycWB+nAJYkhJhm0lzPnJzpvSgYabBxMlEWoiW3Ct0ZmURA==,iv:/R2FOa00XOTBdwsBtpPHlmNEKXRoDgfh73VPs9KY8co=,tag:9hqm88XYrTHHQRe7DJcQGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-05-09T09:26:05Z"
  mac: ENC[AES256_GCM,data:3i7i86ppjv79fxvuxjQrgE0pZ410ZS6VhKVMGiuF2ZCyLul2ndk+vM0EQdYXgtO5k3XFKDlB/uZpXodgvcIiA/o2tC2pNnOWecLs2jbeHaM/ejT8WKO25ho5nbN7i30iwp8hCDVwTY2Yo3XsEjI+NdG2ZvS6zYsdCcGhkmhkMTU=,iv:E8UEK//Np3nDGw+mkiKV2FVnzsaYHsqsVEQOsgIYZDk=,tag:P3SI3V5/vhFen15zCUrQfQ==,type:str]
  pgp:
    - created_at: "2023-05-09T09:26:04Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//d3yfYREZ60I0OR4PAVUc+ol2b3u3vT3PtwF+u0jh3aUK
        6YQpyzGXPmy5SV30vhW0l3uGuryhONsezjtAA9dflnntrCKklvN+soQBGOvD9GNt
        Sg/YyNTTLYFKD7pLUmO3btjPQjy49ORgtw+8Vb2PVJ+N8rR02ResT2UplKk1Ncex
        xyhtBAmtaBYt9ooQAFg5jhhnUfwTAkD7NZTkIag1OdRYB0+1fFZkWLEWYehdhhXV
        0onA2dttJQBG1hc6LxEX6QymevYdqIq3z21QzMVsOGw4+Igrq/vzqmzjq2b7oKmg
        vcB3oV4Kj/kval7cTOReHUoOrHRe2JwngwUkchSRHCTa5h/IwgArBEAsZjZYT+Ve
        6ucT4rDYGikXcT5yKtcwqSEG/0fz2uEUVLDSoB8prQHmQdoE/RaQGirKat1hBdvH
        KH82nbfIOqOsnKa8fTRKxso0Y2t7ofJ9fD8OT0JdE7EYp4sbH4TFFyBg+UlPjgd6
        ijFN2BzT0bmVFs1GgB9Z2Lor9PVW8xzOiYhiI9u1hJ+/0UxfkSxF0dS1mNSoxtGT
        07mr+7vrJD7nq6AV56M55+TrvVEK5yuShrQPxMryYRadY7l5L43/YMUN7kb9Sp+7
        d8PFIiAznXbg2pmX4SFFT+gdh1K+KrfJsHZp1bJjf0zlwKeYAfG3cuuRfpz4oLjU
        aAEJAhDFvrGD6TICxaNthZikcNfgQJTu8H9qW+aczU3naz7WA1xk9r3vDtzH0b9g
        CMPPyiipaylh+u56ZQsCFKgYEz0DzyY079NS3W9cqaIPU5JT5FDXrMB5TVHWLczI
        gypPpTqy1fun
        =auvD
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
