---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["J0n4t4n/flux-home"],
      "dryRun" : "true",
      "flux": {
        "fileMatch": ["\\.yaml$"]
      }
    }
