---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
      interval: 12h
  values:
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb
spec:
  addresses:
    - 10.0.1.0/24
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: vyos
  namespace: metallb
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 10.0.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: vyos
  namespace: metallb
