---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-vanilla
  namespace: flux-system
spec:
  dependsOn:
    - name: minecraft-common
  path: ./apps/minecraft/vanilla/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
