---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-device-plugins-nfd
  namespace: flux-system
spec:
  path: ./deployments/nfd
  prune: true
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-device-plugins-nfd-rules
  namespace: flux-system
spec:
  dependsOn:
    - name: intel-device-plugins-nfd
  path: ./deployments/nfd/overlays/node-feature-rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-device-plugins-gpu
  namespace: flux-system
spec:
  dependsOn:
    - name: intel-device-plugins-nfd-rules
  path: ./deployments/gpu_plugin/overlays/nfd_labeled_nodes
  prune: true
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
