---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container
  namespace: tekton-tasks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeMode: Filesystem
