---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./cilium/ks.yaml
  - ./intel-device-plugins/ks.yaml
  - ./multus/ks.yaml
