---
apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/my-target: internal
    external-dns.alpha.kubernetes.io/hostname: "vanilla.minecraft.k8s.jsteuernagel.de."
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      name: web
      port: 8080
    - targetPort: proxy
      name: proxy
      port: 25565
  selector:
    run: mc-router
