---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: onepassword
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
      interval: 12h
  values:
    operator:
      create: true
      autoRestart: true
      pollingInterval: 600
