apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:ZAVOVYxxuF61rk+cgBBnan60p4Lhell1xjYiTagS8HOjlAW2RJfxTg==,iv:QPXs/uepRsH1xUp0lDZGNgiNDpHcz3fu6N2KzTKa6g4=,tag:YlprZi5qd3chIUhlIqoDXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-03-02T11:33:10Z"
  mac: ENC[AES256_GCM,data:rVmOIhjAo47kMwIERQVJ3MkJT8rGSsquGyzAOLE2ST2zoNOwiZBzoK0o3MeshlfFmJPlLEINZ9ppNgMl0MgWWjnolsvClbnCkH+/dyCebA6nXE55/HgauYthqRP/ru70am16wuBAjHHfxDjxclZ+pV1cZVF7ewZfms+vHdHAAD4=,iv:Y7QLO0Gp/gjM3UCtzS8ZzA2dIHA+a7cpr9nYW4OA+3k=,tag:fxSDLcO8JuYyscS6ZqCEoQ==,type:str]
  pgp:
    - created_at: "2023-03-02T11:33:10Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ/9FWLJJFDlrCd08b4CqSk65YB3WRBFrWa+NgXItgonIv5+
        oPWhx/VqJZCkd4LcdDJAKQETLXEDpW3+eznQ4aiC2Yt0jUHBR+CGHMopB7+o+frS
        Oj50TqeXS52Lsotn33mNSzopZ964spcLsatw864rcNDBcF/bFv10HenxQLV1xM6h
        8e+OZstsE5err61ycPJJrz8l/aNW8vLVx4UUnYYkg2OewSMQkANc9qeZNFiCa6/0
        LWD03+ytHqYHIV6A8I6YPFIPkJzfs7shfQw3UxbdgA2QNZ7BXXhCeJED1H7PS8cS
        3PSgmXi1WGJleVI6OBVpEj3nusvUDkKIZeEwxZep3eqWI04qr3JvUnEYc/frzMoO
        enksv3IYSNlIL+LRpU0quuMkYbJEXDccbimHF7TRACG6xFlnONpQsXSUlOtm6Bm6
        1si0KAhWYI1gG3bVAxOtuOSc+Nb0TzsrCsD5eubcLFd+224xaQcQougpo3WD0ZvO
        juVb8Dby+v/5QWpaqadvoDBayduVnkcJdsz4iBcuHqWoPeDfqKBpdqzbPZOpZjHR
        qwOE79J42/PO5goDGgyFOxxgquYpKQBO/5Xpoy0DwvKrBhpeB4qoD4gcfW26KzK4
        XX8eH10LCwg8G1N/OvbNpxfp/05TovVwChORo+6jN/quaAw/s8ZR0R+uNfBVsRzU
        aAEJAhD3IKDqojI97vi4wL3bs2r5zo1fL6BrIQttWULbb8izysLtynj0PdbLmV+i
        vkpTWe5xKAOT5TOcYGzGR7ho3NfyqcAkhJSIBky4QuipnxJTAKMHpUbUSx06V4SK
        zdEJYO4resGc
        =7gRS
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
