---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: blocky
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-config
  path: ./apps/blocky/blocky/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
