---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
  - https://storage.googleapis.com/tekton-releases/dashboard/latest/release.yaml
  - ingress.yaml
#  - https://api.hub.tekton.dev/v1/resource/tekton/task/github-set-status/0.3/raw

patches:
  - target:
      kind: Namespace
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: tekton-pipelines
