---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: couchdb
  namespace: obsidian
spec:
  interval: 30m
  chart:
    spec:
      chart: couchdb
      version: "4.3.1"
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: flux-system
      interval: 12h
  values:
    clusterSize: 1

    createAdminSecret: false

    persistentVolume:
      enabled: true
      storageClass: "longhorn"
      size: 10Gi

    ingress:
      enabled: true
      hosts:
        - obsidian.jsteuernagel.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/my-target: external
        external-dns.alpha.kubernetes.io/target: dyn.jsteuernagel.de
        nginx.ingress.kubernetes.io/proxy-body-size: 4096m
      tls:
        - hosts:
            - obsidian.jsteuernagel.de
          secretName: obsidian-jsteuernagel-de-tls

    couchdbConfig:
      couchdb:
        uuid: "9b940010-3370-47d8-b789-ad2b49d8207c"
        single_node: true
        max_document_size: 50000000
      chttpd:
        require_valid_user: true
        max_http_request_size: 4294967296
      chttpd_auth:
        require_valid_user: true
        authentication_redirect: "/_utils/session.html"
      httpd:
        WWW-Authenticate: 'Basic realm="couchdb"'
        enable_cors: true
      cors:
        origins: "app://obsidian.md,capacitor://localhost,http://localhost"
        credentials: true
        headers: "accept, authorization, content-type, origin, referer"
        methods: "GET, PUT, POST, HEAD, DELETE"
        max_age: 3600
