---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: system-upgrade
spec:
  interval: 30m
  chart:
    spec:
      chart: kured
      version: "5.3.0"
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
      interval: 12h
  values:
    extraEnvVars:
      - name: notifyHookUrl
        valueFrom:
          secretKeyRef:
            name: kured-hook
            key: notifyHookUrl

    configuration:
      blockingPodSelector: # label selector identifying pods whose presence should prevent reboots
        - reboot=blocked
      startTime: "3:00" # only reboot after this time of day (default "0:00")
      endTime: "6:00" # only reboot before this time of day (default "23:59")
      forceReboot: false # force a reboot even if the drain fails or times out (default: false)
      rebootCommand: "/bin/systemctl reboot" # command to run when a reboot is required by the sentinel
      rebootDelay: "30s" # add a delay after drain finishes but before the reboot command is issued
      notifyUrl: "$(notifyHookUrl)" # notification URL with the syntax as follows: https://containrrr.dev/shoutrrr/services/overview/
      timeZone: "Europe/Berlin" # time-zone to use (valid zones from "time" golang package)
      annotateNodes: true # enable 'weave.works/kured-reboot-in-progress' and 'weave.works/kured-most-recent-reboot-needed' node annotations to signify kured reboot operations
      logFormat: "text" # log format specified as text or json, defaults to text
