---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb
spec:
  addresses:
    - 10.0.0.30-10.0.0.49
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: vyos
  namespace: metallb
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 10.0.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: vyos
  namespace: metallb
