---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: Add Renovate
resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.1/crd.yaml
  - https://github.com/rancher/system-upgrade-controller?ref=v0.13.1
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.13.1
patchesStrategicMerge:
  - |
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: system-upgrade
