---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: blocky
data:
  config.yml: |
    bootstrapDns:
      - upstream: tcp-tls:1.1.1.1:853
      - upstream: tcp-tls:1.0.0.1:853
    upstream:
      default:
        # Digitalcourage dns3
        - "tcp-tls:dns3.digitalcourage.de:853"

        # Mullvad
        - "tcp-tls:doh.mullvad.net:853"
    blocking:
      blackLists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://v.firebog.net/hosts/AdguardDNS.txt
          - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
          - https://www.github.developerdan.com/hosts/lists/dating-services-extended.txt
      whiteLists:
        ads:
          - /app/config/whitelist.txt

      clientGroupsBlock:
        default:
          - ads

    conditional:
      fallbackUpstream: true
      mapping:
        ad.jsteuernagel.de: 10.0.0.80
        home.jsteuernagel.de: 10.0.0.80
        gaia.jsteuernagel.de: 10.0.0.80
        k8s.jsteuernagel.de: 10.0.0.80
    port: 53
  whitelist.txt: |
    # Android Captive
    connectivitycheck.android.com
    clients3.google.com
    connectivitycheck.gstatic.com

    # Apple Music
    itunes.apple.com
    s.mzstatic.com

    # Apple ID
    appleid.apple.com

    # AWS Unified Search
    concierge.analytics.console.aws.a2z.com

    # Battle.Net
    /*.blizzard.com/ #Battle.Net
    /*.battle.net/ #Battle.Net

    # Discord
    cdn.discordapp.com

    # Dropbox
    dl.dropboxusercontent.com
    ns1.dropbox.com
    ns2.dropbox.com

    # Google
    clients4.google.com
    clients2.google.com

    # Google Chrome
    dl.google.com #Google Chrome

    # Google Keep
    reminders-pa.googleapis.com
    firestore.googleapis.com

    # Google Meet
    /beacons?\\d*\\.gvt\\d\\.com$/

    # Google Play
    android.clients.google.com
    0.client-channel.google.com
    2.android.pool.ntp.org

    # GMail
    googleapis.l.google.com

    # iOS
    captive.apple.com
    gsp1.apple.com
    www.apple.com
    www.appleiphonecell.com

    # Microsoft Office
    officeclient.microsoft.com

    # Microsoft Store
    dl.delivery.mp.microsoft.com
    geo-prod.do.dsp.mp.microsoft.com
    displaycatalog.mp.microsoft.com

    # Microsoft Web
    outlook.office365.com
    products.office.com
    c.s-microsoft.com
    i.s-microsoft.com
    login.live.com
    login.microsoftonline.com

    # NVIDIA Geforce Experience
    gfwsl.geforce.com

    # Origin
    cloudsync-prod.s3.amazonaws.com
    cdn.optimizely.com
    s.shopify.com

    # Plex
    plex.tv
    tvdb2.plex.tv
    pubsub.plex.bz
    proxy.plex.bz
    proxy02.pop.ord.plex.bz
    cpms.spop10.ams.plex.bz
    meta-db-worker02.pop.ric.plex.bz
    meta.plex.bz
    tvthemes.plexapp.com.cdn.cloudflare.net
    tvthemes.plexapp.com
    106c06cd218b007d-b1e8a1331f68446599e96a4b46a050f5.ams.plex.services
    meta.plex.tv
    cpms35.spop10.ams.plex.bz
    proxy.plex.tv
    metrics.plex.tv
    pubsub.plex.tv
    status.plex.tv
    www.plex.tv
    node.plexapp.com
    nine.plugins.plexapp.com
    staging.plex.tv
    app.plex.tv
    o1.email.plex.tv
    o2.sg0.plex.tv
    dashboard.plex.tv
    thetvdb.com
    themoviedb.com

    # Qualtrics
    /(\\.|^)qualtrics\\.com$

    # Crunch.io
    /(\\.|^)crunch\\.io$

    # Reddit
    styles.redditmedia.com
    www.redditstatic.com
    reddit.map.fastly.net
    www.redditmedia.com
    reddit-uploaded-media.s3-accelerate.amazonaws.com
    /[a-z]\\.thumbs\\.redditmedia\\.com/
    /(\\.|^)redd\\.it$/
    /(\\.|^)reddit\\.com$/

    # Signal
    ud-chat.signal.org
    chat.signal.org
    storage.signal.org
    signal.org
    www.signal.org
    updates2.signal.org
    textsecure-service-whispersystems.org
    giphy-proxy-production.whispersystems.org
    cdn.signal.org
    whispersystems-textsecure-attachments.s3-accelerate.amazonaws.com
    d83eunklitikj.cloudfront.net
    souqcdn.com
    cms.souqcdn.com
    api.directory.signal.org
    contentproxy.signal.org
    turn1.whispersystems.org

    # Spotify
    spclient.wg.spotify.com
    apresolve.spotify.com

    # Spotify TV
    api-tv.spotify.com

    # Youtube History
    s.youtube.com
    video-stats.l.google.com

    # Youtube iOS App
    www.googleapis.com
    youtubei.googleapis.com
    oauthaccountmanager.googleapis.com

    # Win 10 Update
    sls.update.microsoft.com.akadns.net
    fe3.delivery.dsp.mp.microsoft.com.nsatc.net
    tlu.dl.delivery.mp.microsoft.com
    a-msedge.net
    slscr.update.microsoft.com
    v10.vortex-win.data.microsoft.com
    settings-win.data.microsoft.com

    # Win 10 Captive
    www.msftncsi.com
    msftncsi.com
    ipv6.msftncsi.com

    # XBox Live
    clientconfig.passport.net
    v10.events.data.microsoft.com
    v20.events.data.microsoft.com

    # WhatsApp
    wa.me
    www.wa.me
    /^whatsapp-cdn-shv-[0-9]{2}-[a-z]{3}[0-9]\\.fbcdn\\.net$/
    /^((www|(w[0-9]\\.)?web|media((-[a-z]{3}|\\.[a-z]{4})[0-9]{1,2}-[0-9](\\.|-)(cdn|fna))?)\\.)?whatsapp\\.(com|net)$/

    # Other
    browser.pipe.aria.microsoft.com
    nexusrules.officeapps.live.com
    self.events.data.microsoft.com
    mobile.pipe.aria.microsoft.com
