---
apiVersion: v1
kind: Service
metadata:
  name: blocky-service
  namespace: blocky
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.1.11
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: blocky
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
