---
apiVersion: v1
kind: Service
metadata:
  name: blocky-service
  namespace: blocky
  annotations:
    io.cilium/lb-ipam-ips: 10.0.1.11,fd48:e380:751a:1::11
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: RequireDualStack
  selector:
    app: blocky
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
