---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  itemPath: "vaults/Home Cluster/items/cloudflare-api-token-secret"
