---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pod-security.kubernetes.io/enforce: restricted
