---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 12h
  values:
