---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-router
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium-config
  path: ./apps/minecraft/router/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
