---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: "9.5.1"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 12h
  values:
    image:
      rootless: true
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/my-target: external
        external-dns.alpha.kubernetes.io/target: dyn.jsteuernagel.de
        nginx.ingress.kubernetes.io/proxy-body-size: 4096m
      hosts:
        - host: gitea.jsteuernagel.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.jsteuernagel.de
          secretName: gitea-jsteuernagel-de-tls

    persistence:
      size: 10Gi
      storageClass: longhorn
      # Because of migration from Chart v8
      # Default is now RWX volume, this keeps the old RWO
      mount: true
      create: false
      claimName: data-gitea-0

    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        database:
          DB_TYPE: mysql
          HOST: gitea-mariadb:3306
          NAME: gitea
          USER: gitea
        mailer:
          ENABLED: true
          FROM: gitea@jsteuernagel.de
          MAILER_TYPE: smtp
          SMTP_ADDR: mail.jsteuernagel.de
          SMTP_PORT: 465
          IS_TLS_ENABLED: true
          USER: gitea@jsteuernagel.de
        federation:
          ENABLED: true
        service:
          DISABLE_REGISTRATION: true

        # Workaround for https://gitea.com/gitea/helm-chart/issues/468
        # Can be removed when that issue is fixed
        session:
          PROVIDER: redis-cluster
          PROVIDER_CONFIG: redis+cluster://:gitea@gitea-redis-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
        cache:
          ENABLED: true
          ADAPTER: redis-cluster
          HOST: redis+cluster://:gitea@gitea-redis-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
        queue:
          TYPE: redis
          CONN_STR: redis+cluster://:gitea@gitea-redis-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
      additionalConfigFromEnvs:
        # Migrated from old ENV_TO_INI__ Syntax to GITEA__
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-mariadb-secret
              key: password
        - name: GITEA__MAILER__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-smtp-secret
              key: password
      ldap:
        - name: AD
          securityProtocol: ldaps
          skipTlsVerify: true
          host: "ad.jsteuernagel.de"
          port: "636"
          userSearchBase: "OU=Users,OU=JS,DC=ad,DC=jsteuernagel,DC=de"
          userFilter: "(&(objectClass=user)(sAMAccountName=%s)(memberOf=CN=Gitea User,OU=Groups,OU=JS,DC=ad,DC=jsteuernagel,DC=de))"
          adminFilter: "(memberOf=CN=Gitea Admin,OU=Groups,OU=JS,DC=ad,DC=jsteuernagel,DC=de)"
          existingSecret: gitea-ldap-secret
          usernameAttribute: sAMAccountName
          firstnameAttribute: givenName
          surnameAttribute: sn
          emailAttribute: mail
          publicSSHKeyAttribute: sshPublicKeys

    postgresql-ha:
      enabled: false

    redis-cluster:
      persistence:
        storageClass: local-path