---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: ">=8.0.0 <9.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 12h
  values:
    image:
      rootless: true
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/my-target: external
        external-dns.alpha.kubernetes.io/target: dyn.jsteuernagel.de
      hosts:
        - host: gitea.jsteuernagel.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.jsteuernagel.de
          secretName: gitea-jsteuernagel-de-tls

    persistence:
      size: 10Gi
      storageClass: longhorn

    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        database:
          DB_TYPE: mysql
          HOST: gitea-mariadb:3306
          NAME: gitea
          USER: gitea
      additionalConfigFromEnvs:
        - name: ENV_TO_INI__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-mariadb-secret
              key: password
      ldap:
        - name: AD
          securityProtocol: ldaps
          skipTlsVerify: true
          host: "ad.jsteuernagel.de"
          port: "636"
          userSearchBase: "OU=Users,OU=JS,DC=ad,DC=jsteuernagel,DC=de"
          userFilter: "(&(objectClass=user)(sAMAccountName=%s))"
          adminFilter: "(&(memberOf=CN=Gitea Admin,OU=Groups,OU=JS,DC=ad,DC=jsteuernagel,DC=de))"
          existingSecret: gitea-ldap-secret
          usernameAttribute: CN
          firstnameAttribute: givenName
          surnameAttribute: sn
          emailAttribute: mail
          publicSSHKeyAttribute: sshPublicKeys

    postgresql:
      enabled: false
