apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: gitea
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:s8iNDhh5LCLFWII=,iv:WZ53+VTAaAIDJn9Rt2LLGRZTfkvlOWiUgen5qILWexc=,tag:5VcMlgoq8xwOIrEttUxFGQ==,type:str]
  password: ENC[AES256_GCM,data:58pDZGJSI7YGRwyq2bOZTfsrp1sTuco/n4tHCXPS,iv:InuWCryGMih+F9xgc+VqEQ8UNIRdvSGLsPxHzus/vHc=,tag:gjt9/IgxoHRztTfSotpuGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-04-26T09:36:14Z"
  mac: ENC[AES256_GCM,data:eEPA8Wtn8Uihzl50n/Rz9rmsjsCBDqHaxRsNVKJnJqdtjNmx82sBZx8N5TicKNwTklTk2nV7E07QoA6X53pF2Pcx5c1tCZAHqeTVjTuWR1kDRfrtZMad0fzT6QWdqqkXpGNuUpbyMJWJFWV3HXUMYq6Juh5Zkji9bXSxIcLZak8=,iv:zomXTIejnzc72ajKjJKLUvmkpniu+9Io6OrA/DGcJAs=,tag:sM4HDcVDhR2gBZYiTkzgQg==,type:str]
  pgp:
    - created_at: "2023-04-26T09:36:14Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//dJEWHkxAGrfXVGQa+bIr22D+2ZyLbir3FOnGiTj8xU8F
        yeSP15OY5KdIuWb/TsjxIrW79uoly0nPZwZgTqKtKJNevHKjlgggivLbvGO2jZ9O
        1mksFH4T7HGbVD1tmIKcfVz9/UOemJQzDrM68r+4QByseYQErs2czzRPPnYsm4U8
        nf+BjdPZIWieBYRRF6zdVkTSLKurWp94Nh16PLxiWQZ7Mq/AiSp48ieXXfz353QT
        e0RqF65pWf07HRLY+Xii4ywezwVcAbT80h7Uhn/dtRRp6TelxJlab8u6rOY5kt3R
        K8dSK4maA2hcSeKjvOZzPpfh8qLbhUChGY1AYi3+zkvWepBpiOcxgSqtgVAla8Fd
        tgQHKtgGusSl/iNOCv1HtmsGPU+xRBJEqm52kfvcjzhiGz1pKoDinMK+JRjepXfM
        TwK6iiutqSnTeZFKCqFevWGLP8Q6zOCiEvJh5Q8qo29Oi0o5sN7pkQFMVikH/hf3
        ZnXpTdv8sfZlHSL5bjUmvVSBIY4uTp9kzP2aIPSeTeMhbm8koKBgBhrSMD/RA4v8
        1+wSeSyXU30NQSX3UH3LHnezBCM/cSQG7YPwLpqz9JzCDOxWAarOPFYNYYlE5yJI
        ufCWLo6hVCTyKiBZ5+kj5R+/gFB/uXfVjTdkosKNhvBuv4SWmUXZZppYLIaEgKPU
        aAEJAhDo4x+lCT1GMA+DIspeyuq1AFZqge581FUXH/RJMvkUh7Zh3yREs0pYYzpe
        TPAUk7u86lg22oKyBnlBMcLum7XcoJgM+AKnwitw6SC4vdL8eFJYavcC+DTVyAT5
        enOvVNX5jr5A
        =c2Vf
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-ldap-secret
  namespace: gitea
type: Opaque
stringData:
  bindDn: ENC[AES256_GCM,data:zx3CBn0Ap1NPrvKcwxjbWOs4nobL3xY2stQEjs8Znta5t2JODxtozvkp4m6dRJFNw9LBAHAjuzhEnBEUefJM1rssf9z/WA==,iv:NG96xaWc5lSsJDewZaW7MTU4q6qDdlmcf9fYneXa3+U=,tag:GkPYax/Inrg/kEcrMiogdA==,type:str]
  bindPassword: ENC[AES256_GCM,data:FEDusTADsNG0zNLFM2SwFvkmYzZhLw+FpbxUYoeU,iv:0OvsvHBSjTIL8bzEdWdyhPKT61rIU0YPMkpzSL9SthE=,tag:gBeY7qrIT1cGtwcFdH5MYA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-04-26T09:36:14Z"
  mac: ENC[AES256_GCM,data:eEPA8Wtn8Uihzl50n/Rz9rmsjsCBDqHaxRsNVKJnJqdtjNmx82sBZx8N5TicKNwTklTk2nV7E07QoA6X53pF2Pcx5c1tCZAHqeTVjTuWR1kDRfrtZMad0fzT6QWdqqkXpGNuUpbyMJWJFWV3HXUMYq6Juh5Zkji9bXSxIcLZak8=,iv:zomXTIejnzc72ajKjJKLUvmkpniu+9Io6OrA/DGcJAs=,tag:sM4HDcVDhR2gBZYiTkzgQg==,type:str]
  pgp:
    - created_at: "2023-04-26T09:36:14Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//dJEWHkxAGrfXVGQa+bIr22D+2ZyLbir3FOnGiTj8xU8F
        yeSP15OY5KdIuWb/TsjxIrW79uoly0nPZwZgTqKtKJNevHKjlgggivLbvGO2jZ9O
        1mksFH4T7HGbVD1tmIKcfVz9/UOemJQzDrM68r+4QByseYQErs2czzRPPnYsm4U8
        nf+BjdPZIWieBYRRF6zdVkTSLKurWp94Nh16PLxiWQZ7Mq/AiSp48ieXXfz353QT
        e0RqF65pWf07HRLY+Xii4ywezwVcAbT80h7Uhn/dtRRp6TelxJlab8u6rOY5kt3R
        K8dSK4maA2hcSeKjvOZzPpfh8qLbhUChGY1AYi3+zkvWepBpiOcxgSqtgVAla8Fd
        tgQHKtgGusSl/iNOCv1HtmsGPU+xRBJEqm52kfvcjzhiGz1pKoDinMK+JRjepXfM
        TwK6iiutqSnTeZFKCqFevWGLP8Q6zOCiEvJh5Q8qo29Oi0o5sN7pkQFMVikH/hf3
        ZnXpTdv8sfZlHSL5bjUmvVSBIY4uTp9kzP2aIPSeTeMhbm8koKBgBhrSMD/RA4v8
        1+wSeSyXU30NQSX3UH3LHnezBCM/cSQG7YPwLpqz9JzCDOxWAarOPFYNYYlE5yJI
        ufCWLo6hVCTyKiBZ5+kj5R+/gFB/uXfVjTdkosKNhvBuv4SWmUXZZppYLIaEgKPU
        aAEJAhDo4x+lCT1GMA+DIspeyuq1AFZqge581FUXH/RJMvkUh7Zh3yREs0pYYzpe
        TPAUk7u86lg22oKyBnlBMcLum7XcoJgM+AKnwitw6SC4vdL8eFJYavcC+DTVyAT5
        enOvVNX5jr5A
        =c2Vf
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-mariadb-secret
  namespace: gitea
type: Opaque
stringData:
  root-password: ENC[AES256_GCM,data:6IPPRuQclCwpjmzlAyCGxTRHt2JYqrJRNqZcMfmJ,iv:BoRRZ1nCMij/qZa7vXI6QfJwaq/yEETj5FRD+MMCsa0=,tag:5miR6iYvhAiXUn8fPbHQrA==,type:str]
  password: ENC[AES256_GCM,data:Qh/am/xDmWA308/UquMNkGW5a5YUye4q2KudbpIu,iv:oswazNxxE2NDLC94M4Uy2k3MgT0b09HcOly7fxToIpc=,tag:Ek8g4RF6dc2aY/enyL8lkQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-04-26T09:36:14Z"
  mac: ENC[AES256_GCM,data:eEPA8Wtn8Uihzl50n/Rz9rmsjsCBDqHaxRsNVKJnJqdtjNmx82sBZx8N5TicKNwTklTk2nV7E07QoA6X53pF2Pcx5c1tCZAHqeTVjTuWR1kDRfrtZMad0fzT6QWdqqkXpGNuUpbyMJWJFWV3HXUMYq6Juh5Zkji9bXSxIcLZak8=,iv:zomXTIejnzc72ajKjJKLUvmkpniu+9Io6OrA/DGcJAs=,tag:sM4HDcVDhR2gBZYiTkzgQg==,type:str]
  pgp:
    - created_at: "2023-04-26T09:36:14Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//dJEWHkxAGrfXVGQa+bIr22D+2ZyLbir3FOnGiTj8xU8F
        yeSP15OY5KdIuWb/TsjxIrW79uoly0nPZwZgTqKtKJNevHKjlgggivLbvGO2jZ9O
        1mksFH4T7HGbVD1tmIKcfVz9/UOemJQzDrM68r+4QByseYQErs2czzRPPnYsm4U8
        nf+BjdPZIWieBYRRF6zdVkTSLKurWp94Nh16PLxiWQZ7Mq/AiSp48ieXXfz353QT
        e0RqF65pWf07HRLY+Xii4ywezwVcAbT80h7Uhn/dtRRp6TelxJlab8u6rOY5kt3R
        K8dSK4maA2hcSeKjvOZzPpfh8qLbhUChGY1AYi3+zkvWepBpiOcxgSqtgVAla8Fd
        tgQHKtgGusSl/iNOCv1HtmsGPU+xRBJEqm52kfvcjzhiGz1pKoDinMK+JRjepXfM
        TwK6iiutqSnTeZFKCqFevWGLP8Q6zOCiEvJh5Q8qo29Oi0o5sN7pkQFMVikH/hf3
        ZnXpTdv8sfZlHSL5bjUmvVSBIY4uTp9kzP2aIPSeTeMhbm8koKBgBhrSMD/RA4v8
        1+wSeSyXU30NQSX3UH3LHnezBCM/cSQG7YPwLpqz9JzCDOxWAarOPFYNYYlE5yJI
        ufCWLo6hVCTyKiBZ5+kj5R+/gFB/uXfVjTdkosKNhvBuv4SWmUXZZppYLIaEgKPU
        aAEJAhDo4x+lCT1GMA+DIspeyuq1AFZqge581FUXH/RJMvkUh7Zh3yREs0pYYzpe
        TPAUk7u86lg22oKyBnlBMcLum7XcoJgM+AKnwitw6SC4vdL8eFJYavcC+DTVyAT5
        enOvVNX5jr5A
        =c2Vf
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
