apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: gitea
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:hNzk0IY=,iv:lta3vv5fi/bW8344OKL8t/6W9v9nVeoP3zeCvg7b+uM=,tag:wHSjqYzKaEwVfQfSBUw52w==,type:str]
  password: ENC[AES256_GCM,data:vhLLQPReIzXZNapDtH72K04prkgwzjyOj3XyFptR,iv:ogCma1Y21w/4x2LAkRVLvamuN33UFdWUJEG32qkSj9g=,tag:lTLfFjVhzWaMMp6FqHi8Hw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-04-26T09:09:27Z"
  mac: ENC[AES256_GCM,data:H3SkJj3YeSmaJTHiy4frC2RfMveocPhCtbYAADcw0QGELlW17OeL5TFMtDFAXbgEH3LX0K6KS2vIeb2JFJ4KXhNDIPhx0K5dsVGqA9Je3748nobXUtY4BxloCWFj3fF/rJ0S8INpuqhl/Qteo6gc4H1C29lPz9RjJNhU+WKSlDk=,iv:HE01oXnEP9ejWKXCK+XIpi4qr+sOkrA8x0z7NJV8TSo=,tag:5SIv6xOUJ4nu8aiSsDjkxg==,type:str]
  pgp:
    - created_at: "2023-04-26T09:09:26Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//WyGdwBoZYAX29N7DMx0TofZkIKrTl5JjHf+Rd5j5aB3h
        N9jlHxSxbtvcfbTssKLan91qiu5h20g3eePjgTN6/WEMh1q6eD4yCSlwdPKtulg9
        CvETKqDboL3oy0/blep/L0wKHUAvAfNbRPxcFjsuVEU59devzDJd5xWhlVFz3M8/
        LIhbV4T24m4TMReZVcCrXb0+bXlQGZQSiFXHklgO0KWzMW2m55sWMcyn+V9Mrvai
        3HppZL0iqsnIIihEKTKBsK8PAGRINGiofWB7QlM9YGDokUqYSzmeNkparxefiQG9
        K1wWCP3F6Hu5T8IeULsIRZZXUYi8X4oLF511NLQ+csgirZeq5S5vo2LT3/gfzcC9
        A954hD/e9iYrehyK1KcZfRrzqvyvi8aOsruMTQhtI8tiHeW/CaLuJSU8EpD2flD+
        uSbeTaCrWyvNI2RNjWKofLrg9DpjMT/qDYy6dgKkQuxrLLC3VnZSMf0d5FoBYPkp
        UpbhYydoleJ1Eceq4jkVgLZdlJedhLXHKj9Sy8zBNThcJ3ON5cny0o+d8vXfylIa
        rHwOqhIH5qoMqZJmSqM1ZHjbpEEekGNdxIF/j0Gu/dw53Ut1Cnjl71Z3lQHLXhFw
        jAH1nF6fAhkGdfyHvU02rINH7JTwA8TLnUvC22IOjEgQ28giDBpH73o1a9G5QAfU
        ZgEJAhDoyNUdWyzDIKUMO2Tz9qE8pRMGRUvUn3ya1P248k6dUgWcLDYTmI5426zX
        XOFQ6Hb4BwJKzHaIODrbOw+jCdmGveH5lzNR2FsHrQj3IiR63imgAF0A5/C1r0CY
        UZiBxn6aYA==
        =OnIG
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-ldap-secret
  namespace: gitea
type: Opaque
stringData:
  bindDn: ENC[AES256_GCM,data:V3WewOnx9oUxNoM4g8uD65lRZFBwIXjm7lIKgsUZb7Ei8mkTFMryuUyoCXvMYFofWeesZV/cd135LHcKO00xe/u7rhjP3w==,iv:5vhsvoOu2zyHonUzf1WJiUoA1p6kiUYTKTSda7jvULU=,tag:La0NZ8WemOjsQBIf4Y3G1w==,type:str]
  bindPassword: ENC[AES256_GCM,data:4edn9h645V6t1O693mUPrAvNP0Yguowv5xl8wTRF,iv:j8XUt0EjyWKsfwEZ2+1FhPo08XQiflgIKMM0deEEiOg=,tag:qW6VdkEdPSq2bhyLvJuLbQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-04-26T09:09:27Z"
  mac: ENC[AES256_GCM,data:H3SkJj3YeSmaJTHiy4frC2RfMveocPhCtbYAADcw0QGELlW17OeL5TFMtDFAXbgEH3LX0K6KS2vIeb2JFJ4KXhNDIPhx0K5dsVGqA9Je3748nobXUtY4BxloCWFj3fF/rJ0S8INpuqhl/Qteo6gc4H1C29lPz9RjJNhU+WKSlDk=,iv:HE01oXnEP9ejWKXCK+XIpi4qr+sOkrA8x0z7NJV8TSo=,tag:5SIv6xOUJ4nu8aiSsDjkxg==,type:str]
  pgp:
    - created_at: "2023-04-26T09:09:26Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//WyGdwBoZYAX29N7DMx0TofZkIKrTl5JjHf+Rd5j5aB3h
        N9jlHxSxbtvcfbTssKLan91qiu5h20g3eePjgTN6/WEMh1q6eD4yCSlwdPKtulg9
        CvETKqDboL3oy0/blep/L0wKHUAvAfNbRPxcFjsuVEU59devzDJd5xWhlVFz3M8/
        LIhbV4T24m4TMReZVcCrXb0+bXlQGZQSiFXHklgO0KWzMW2m55sWMcyn+V9Mrvai
        3HppZL0iqsnIIihEKTKBsK8PAGRINGiofWB7QlM9YGDokUqYSzmeNkparxefiQG9
        K1wWCP3F6Hu5T8IeULsIRZZXUYi8X4oLF511NLQ+csgirZeq5S5vo2LT3/gfzcC9
        A954hD/e9iYrehyK1KcZfRrzqvyvi8aOsruMTQhtI8tiHeW/CaLuJSU8EpD2flD+
        uSbeTaCrWyvNI2RNjWKofLrg9DpjMT/qDYy6dgKkQuxrLLC3VnZSMf0d5FoBYPkp
        UpbhYydoleJ1Eceq4jkVgLZdlJedhLXHKj9Sy8zBNThcJ3ON5cny0o+d8vXfylIa
        rHwOqhIH5qoMqZJmSqM1ZHjbpEEekGNdxIF/j0Gu/dw53Ut1Cnjl71Z3lQHLXhFw
        jAH1nF6fAhkGdfyHvU02rINH7JTwA8TLnUvC22IOjEgQ28giDBpH73o1a9G5QAfU
        ZgEJAhDoyNUdWyzDIKUMO2Tz9qE8pRMGRUvUn3ya1P248k6dUgWcLDYTmI5426zX
        XOFQ6Hb4BwJKzHaIODrbOw+jCdmGveH5lzNR2FsHrQj3IiR63imgAF0A5/C1r0CY
        UZiBxn6aYA==
        =OnIG
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-mariadb-secret
  namespace: gitea
type: Opaque
stringData:
  root-password: ENC[AES256_GCM,data:BPynndHH+TAtBYXtUK9nkbKAjmkByTvk1NrW/s7V,iv:xaM6itqKg9kR5NHdgRynhgir70cO6nlP8OqJLPLFPt4=,tag:Fzss9lKpgYN4su7mzJEmwg==,type:str]
  password: ENC[AES256_GCM,data:Gbfvl3euIiR5TYUP4flU7otIJYg0hlZgpjuoagHr,iv:Uyl3rIRXiRWr/Fzw7tc5EzpdPVxmZffbOKshr0BstGg=,tag:nJQTcmlehBeFqYkK2M390w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-04-26T09:09:27Z"
  mac: ENC[AES256_GCM,data:H3SkJj3YeSmaJTHiy4frC2RfMveocPhCtbYAADcw0QGELlW17OeL5TFMtDFAXbgEH3LX0K6KS2vIeb2JFJ4KXhNDIPhx0K5dsVGqA9Je3748nobXUtY4BxloCWFj3fF/rJ0S8INpuqhl/Qteo6gc4H1C29lPz9RjJNhU+WKSlDk=,iv:HE01oXnEP9ejWKXCK+XIpi4qr+sOkrA8x0z7NJV8TSo=,tag:5SIv6xOUJ4nu8aiSsDjkxg==,type:str]
  pgp:
    - created_at: "2023-04-26T09:09:26Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAziw5H14r1eiAQ//WyGdwBoZYAX29N7DMx0TofZkIKrTl5JjHf+Rd5j5aB3h
        N9jlHxSxbtvcfbTssKLan91qiu5h20g3eePjgTN6/WEMh1q6eD4yCSlwdPKtulg9
        CvETKqDboL3oy0/blep/L0wKHUAvAfNbRPxcFjsuVEU59devzDJd5xWhlVFz3M8/
        LIhbV4T24m4TMReZVcCrXb0+bXlQGZQSiFXHklgO0KWzMW2m55sWMcyn+V9Mrvai
        3HppZL0iqsnIIihEKTKBsK8PAGRINGiofWB7QlM9YGDokUqYSzmeNkparxefiQG9
        K1wWCP3F6Hu5T8IeULsIRZZXUYi8X4oLF511NLQ+csgirZeq5S5vo2LT3/gfzcC9
        A954hD/e9iYrehyK1KcZfRrzqvyvi8aOsruMTQhtI8tiHeW/CaLuJSU8EpD2flD+
        uSbeTaCrWyvNI2RNjWKofLrg9DpjMT/qDYy6dgKkQuxrLLC3VnZSMf0d5FoBYPkp
        UpbhYydoleJ1Eceq4jkVgLZdlJedhLXHKj9Sy8zBNThcJ3ON5cny0o+d8vXfylIa
        rHwOqhIH5qoMqZJmSqM1ZHjbpEEekGNdxIF/j0Gu/dw53Ut1Cnjl71Z3lQHLXhFw
        jAH1nF6fAhkGdfyHvU02rINH7JTwA8TLnUvC22IOjEgQ28giDBpH73o1a9G5QAfU
        ZgEJAhDoyNUdWyzDIKUMO2Tz9qE8pRMGRUvUn3ya1P248k6dUgWcLDYTmI5426zX
        XOFQ6Hb4BwJKzHaIODrbOw+jCdmGveH5lzNR2FsHrQj3IiR63imgAF0A5/C1r0CY
        UZiBxn6aYA==
        =OnIG
        -----END PGP MESSAGE-----
      fp: 88DCC42200E0ECBA88A3A3683422AE3CB0AE74A0
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
