---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: ./script/helm/garage
      version: "*"
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 12h
  values:
    garage:
      replicationMode: "3"

    deployment:
      replicaCount: 3

    persistence:
      meta:
        storageClass: "local-path"
        size: 1Gi
      data:
        storageClass: "local-path"
        size: 10Gi

    service:
      type: LoadBalancer
