---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: ./script/helm/garage
      version: "*"
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 12h
  values:
    garage:
      dbEngine: "lmdb"

      replicationMode: "3"
      s3:
        api:
          rootDomain: ".s3.jsteuernagel.de"
        web:
          rootDomain: ".web.jsteuernagel.de"

    deployment:
      replicaCount: 3

    persistence:
      meta:
        storageClass: "local-path"
        size: 5Gi
      data:
        storageClass: "local-path"
        size: 50Gi

    service:
      type: LoadBalancer
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Service
              name: garage
            patch:
              - op: add
                path: "/metadata/annotations/io.cilium~1lb-ipam-ips"
                value: "10.0.1.196,fd48:e380:751a:1::20"
              - op: add
                path: "/spec/ipFamilyPolicy"
                value: PreferDualStack