---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: ./script/helm/garage
      version: "*"
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 12h
  values:
    garage:
      dbEngine: "lmdb"

      replicationMode: "3"
      s3:
        api:
          rootDomain: ".s3.jsteuernagel.de"
        web:
          rootDomain: ".web.jsteuernagel.de"

    deployment:
      replicaCount: 3

    persistence:
      meta:
        storageClass: "local-path"
        size: 5Gi
      data:
        storageClass: "local-path"
        size: 50Gi

    service:
      type: LoadBalancer
