---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: ./script/helm/garage
      version: "*"
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 12h
  values:
    garage:
      replicationMode: "2"

    deployment:
      replicaCount: 2

    persistence:
      meta:
        storageClass: "local-path"
        size: 100Mi
      data:
        storageClass: "local-path"
        size: 1Gi

    ingress:
      s3:
        api:
          enabled: true
          className: "nginx"
          annotations:
            external-dns.alpha.kubernetes.io/my-target: external
            external-dns.alpha.kubernetes.io/target: home.jsteuernagel.de
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: s3-api.jsteuernagel.de
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: s3-api-jsteuernagel-de-tls
              hosts:
                - s3-api.jsteuernagel.de
