---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: ./script/helm/garage
      version: "*"
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 12h
  values:
    garage:
      replicationMode: "3"

    deployment:
      replicaCount: 3

    persistence:
      meta:
        storageClass: "local-path"
        size: 1Gi
      data:
        storageClass: "local-path"
        size: 10Gi

    ingress:
      s3:
        api:
          enabled: true
          className: "nginx"
          annotations:
            external-dns.alpha.kubernetes.io/my-target: external
            external-dns.alpha.kubernetes.io/target: dyn.jsteuernagel.de
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: "s3.jsteuernagel.de"
              paths:
                - path: /
                  pathType: Prefix
            - host: "*.s3.jsteuernagel.de"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: s3-jsteuernagel-de-tls
              hosts:
                - s3.jsteuernagel.de
