---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: Add Renovate
bases:
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd?ref=v0.26.0
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v0.26.0
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin/overlays/nfd_labeled_nodes?ref=v0.26.0

patches:
  - path: add-namespace.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: intel-gpu-plugin
