---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: homeassistant
data:
  mosquitto.conf: |
    listener 1883
    protocol mqtt

    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout
    log_timestamp true
    log_timestamp_format %Y-%m-%dT%H:%M:%S

    password_file /mosquitto/password/pwfile
