---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      strategy:
        type: Recreate
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.17-openssl
          ports:
            - containerPort: 1883
          volumeMounts:
            - mountPath: /mosquitto/config
              readOnly: true
              name: config
            - mountPath: /mosquitto/password
              readOnly: true
              name: password
            - mountPath: /mosquitto/data
              name: data
          env:
            - name: PUID
              value: "1883"
            - name: PGID
              value: "1883"
          securityContext:
            runAsUser: 1883
            runAsGroup: 1883
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: password
          secret:
            secretName: mosquitto-passwordfile
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
