---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-svc
  namespace: homeassistant
  annotations:
    external-dns.alpha.kubernetes.io/my-target: internal
    external-dns.alpha.kubernetes.io/hostname: mosquitto.k8s.jsteuernagel.de
spec:
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
