---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium-config
  path: ./deployments/multus-daemonset-thick.yml
  targetNamespace: kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: multus
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
