---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanilla-data
  namespace: minecraft
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
