---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-sa
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-role
  namespace: actions-runner-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-rolebinding
  namespace: actions-runner-system
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount
    name: runner-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-role
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-silverblue-runners
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: J0n4t4n/my-silverblue
      containerMode: kubernetes
      serviceAccountName: runner-sa
      workVolumeClaimTemplate:
        storageClassName: longhorn
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 5Gi
      env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: my-silverblue-runners
  namespace: actions-runner-system
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: my-silverblue-runners
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
