---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: ot-operators
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
      interval: 12h
  values:
