---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: bind
  annotations:
    io.cilium/lb-ipam-ips: fd48:e380:751a:1::12
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - "IPv6"
  selector:
    app: bind
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: bind-udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: bind-tcp
